# NumPy
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object

* sophisticated (broadcasting) functions

* tools for integrating C/C++ and Fortran code

* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. 
Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.
## The Basics
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.
For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.
```python
[[ 1., 0., 0.],
 [ 0., 1., 2.]]
```
The more important attributes of an ndarray object are:
<b> ndim, shape, size, dtype, itemsize, data <b>

In [1]:
import numpy as np
a = np.arange(15).reshape(3,5)      # To create sequences of numbers, NumPy provides a function analogous to range that returns
                                    # arrays instead of lists.
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


+ When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [48]:
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)
print(f)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

In [9]:
a.ndim

2

In [10]:
a.shape

(3, 5)

In [11]:
a.size

15

In [15]:
a.dtype

dtype('int32')

In [16]:
a.itemsize

4

In [21]:
a.data

## Array Creation

In [37]:
n = np.array([[2,3,4],[1,2,3]])
print(n)
print(type(n))

#The dtype of the array

[[2. 3. 4.]
 [1. 2. 3.]]
<class 'numpy.ndarray'>


In [25]:
n.shape

(2, 3)

In [31]:
n.dtype

dtype('int32')

+ Often, the elements of an array are originally unknown, but its size is known. Hence, <b> NumPy offers several functions to create arrays with initial placeholder content.</b> These minimize the necessity of growing arrays, an expensive operation.

+ The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default,<b> the dtype of the created array is float64.</b>

In [39]:
np.zeros((3,4))

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [41]:
np.ones((3,2,3))                        # a 3D array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
np.empty( (2,3) )                                 # uninitialized, output may vary

array([[1., 1., 1.],
       [1., 1., 1.]])

## Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [49]:
 a = np.array( [20,30,40,50] )
b = np.arange( 4 )

# c = a-b

# b**2

# 10*np.sin(a)

# a<35


+ Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [55]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
# A * B                       # # elementwise product

# A @ B                       # matrix product

# A.dot(B)                    # another matrix product

# Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))

# a *= 3

# b += a

# a += b                  # b is not automatically converted to integer type

In [61]:
'''Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods
of the ndarray class.'''



'Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods\nof the ndarray class.'

<b> By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:</b>

## Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

+ Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:
```python
[0 0 0      [0 0 0      [0 0 0      [0 0 0
 0 0 0]      0 0 0]      0 0 0]      0 0 0]             <- 
```

In [2]:
a = np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [3]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])

In [11]:
a[2:][:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [88]:
c[1,...]                     #  NumPy also allows you to write this using dots as b[i,...].

                             # The dots (...) represent as many colons as needed to produce a complete indexing tuple.

array([[100, 101, 102],
       [110, 112, 113]])

In [89]:
# Iterating over multidimensional arrays is done with respect to the first axis:


## Stacking together different arrays

Several arrays can be stacked together along different axes:

In [94]:
a = np.floor(10*np.random.random((2,2)))

In [95]:
b = np.floor(10*np.random.random((2,2)))

In [96]:
np.vstack((a,b))

array([[8., 0.],
       [2., 0.],
       [1., 8.],
       [3., 6.]])

In [27]:
# column_stack
a = np.floor(10*np.random.random((5)))
b = np.floor(10*np.random.random((5)))
print(a)
print(b)

[8. 0. 8. 3. 3.]
[1. 2. 1. 4. 2.]



<b> numpy.hstack(tup) </b>

Stack arrays in sequence horizontally (column wise).

This is equivalent to concatenation along the second axis, except for 1-D arrays where it concatenates along the first axis. Rebuilds arrays divided by hsplit.

This function makes most sense for arrays with up to 3 dimensions. For instance, for pixel-data with a height (first axis), width (second axis), and r/g/b channels (third axis). The functions concatenate, stack and block provide more general stacking and concatenation operations.

<b>Parameters:</b>	
tup : sequence of ndarrays
The arrays must have the same shape along all but the second axis, except 1-D arrays which can be any length.

<b>Returns:</b>	
stacked : ndarray
The array formed by stacking the given arrays.



In [90]:
# a = np.array((1,2,3))
# b = np.array((2,3,4))



# a = np.array([[1],[2],[3]])
# b = np.array([[2],[3],[4]])


<b>vstack</b>

In [93]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])

(6, 1)

In [9]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

In [14]:
a

array([[3., 2.],
       [2., 9.]])

In [15]:
b

array([[0., 4.],
       [0., 7.]])